name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build site
        run: |
          mkdir build
          cp docs/favicon.ico build/favicon.ico

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: build

      - name: Deploy to Nekoweb
        uses: mp-pinheiro/nekoweb-deploy@0.2.1
        with:
          API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
          BUILD_DIR: './build'
          DEPLOY_DIR: '/nekoapi'
          CLEANUP: 'False'
          DELAY: '0.5'
          NEKOWEB_PAGENAME: 'jefbecker'
          ENCRYPTION_KEY: ${{ secrets.NEKOWEB_ENCRYPTION_KEY }}
